### ISSUE TITLE
Delete after Download

### ISSUE THREAD

**Issue by ClarkJeff** [ElanHasson/SSIS-Extensions#7]
Is there a way to delete (manually or automatically) the remote FTP file after receiving it successfully?  

I saw that this was an issue in the prior 2012 version that was fixed in March, 2014, but it doesn't appear to work in this version ([https://ssisextensions.codeplex.com/discussions/442856]).

I'd be ok with a separate File Action, "Delete File(s)" instead of/in addition to enabling the Remove Remote after download.

That way, I can make sure the downloaded file processed successfully before actually deleting it from the FTP site.

Thanks!

**Comment by ClarkJeff** [comment]
Nevermind....  the Remove Remote actually does appear to be working as designed.  I'm not sure why I didn't think it did, but I've confirmed it's ok.  Thanks!

**Comment by ElanHasson** [comment]
Thanks for taking care of this.

If you're interested in contributing , go ahead ;)

**Comment by ClarkJeff** [comment]
Elan,


What version of Visual Studio did you use?


It looks like it needs an Installer plug-in/module as well, do you recall which one that was?


Thanks!


Jeff Clark


________________________________

**Comment by chrhon** [comment]
Hey Jeff,

Elan listed it all out on the main page https://github.com/ElanHasson/SSIS-Extensions (fyi its 2012).

I was able to get it working in VS 2015 (the community / free edition) despite the errors about missing a plug-in – the plug in its erroring out on as far as I can tell is related to creating the installer (so after my work on it I have to deploy through visual studio or manually copy the files and register since I didn’t make a new installer).   Overall the project is kind of messy as there are lots of things in there that don’t appear to be required (probably not Elan’s fault) – if you are working on it to recompile to 2016 (as I did) or tweaking some features etc. you really only need to grab the 2014 folder, and create a new project based on the contents of that folder in Visual Studio (see screenshot)  
![2017-01-17_13h01_22](https://cloud.githubusercontent.com/assets/22528551/22035599/23b04692-dcb6-11e6-949b-0314989b98fe.jpg)

I hope that helps!

Chris

**Comment by ElanHasson** [comment]
I think it uses Wix. It's a add-on project type. http://wixtoolset.org

**Comment by ClarkJeff** [comment]
Another question...


When I want to promote/deploy my SSIS project using your extensions to Production, do I need to install anything on the Production server?


I just deployed it and am getting errors, so wanted to check before I researched too much.


Thanks!


Jeff Clark


________________________________

**Comment by ClarkJeff** [comment]
I just read some of the Discussions on the website and it sounds like i do need to run the Setup in Production as well.


I'll  try that now.

Thanks.


Jeff Clark


________________________________
